-- MySQL Script generated by MySQL Workbench
-- Fri Mar 13 13:49:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema autoscout69
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema autoscout69
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autoscout69` DEFAULT CHARACTER SET utf8 ;
USE `autoscout69` ;

-- -----------------------------------------------------
-- Table `autoscout69`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoscout69`.`User` (
  `id` INT NOT NULL,
  `username` VARCHAR(90) NOT NULL,
  `password` BLOB NOT NULL,
  `email` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoscout69`.`Car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoscout69`.`Car` (
  `id` INT NOT NULL,
  `name` VARCHAR(90) NOT NULL,
  `price` INT NOT NULL,
  `brand` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoscout69`.`selledcars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoscout69`.`selledcars` (
  `user_id` INT NOT NULL,
  `car_id` INT NOT NULL,
  `timestamp` BIGINT NOT NULL,
  PRIMARY KEY (`user_id`, `car_id`),
  INDEX `fk_User_has_Car_Car1_idx` (`car_id` ASC),
  INDEX `fk_User_has_Car_User_idx` (`user_id` ASC),
  CONSTRAINT `fk_User_has_Car_User`
    FOREIGN KEY (`user_id`)
    REFERENCES `autoscout69`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Car_Car1`
    FOREIGN KEY (`car_id`)
    REFERENCES `autoscout69`.`Car` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
